###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"rahulA",
    "username":"rahul143",
    "password": "rahul@123",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"rahul143",
    "password": "rahul@123"
}